name: ifj-project

on:
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@main
            - name: build application
              run: make build
            - name: test application
              run: make test
